# Default values for mariadb.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# note that you need to update the gcomm member list
# below when changing this value
replicas: 3

# this drives the service name, and statefulset name
service_name: mariadb

images:
  mariadb: quay.io/stackanetes/stackanetes-mariadb:newton

volume:
  class_path: volume.beta.kubernetes.io/storage-class
  class_name: general
  size: 20Gi

labels:
  node_selector_key: mariadb-server
  node_selector_value: enabled

network:
  port:
    wsrep: 4567
    mariadb: 3306
    ist: 4444
  dns:
    kubernetes_domain: cluster.local

database:
  root_password: password
  cluster_name: mariadb
  node_name: master
